---
title: "Validation of microglial content in FACS cells from injured spinal cord"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
#Installing packages
# install.packages("ggplot2")
# install.packages("data.table")
# install.packages("cowplot")
# install.packages("RColorBrewer")

#Attaching packages
library(ggplot2)
library(data.table)
library(cowplot)
library(RColorBrewer)

rm(list=ls())

source("/home/ramhak/Dropbox/PHD/PAPER I/R_v2/Function_directory/RTqPCR_data_output_adjuster.R")
```

```{r error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
#1. Importing data
DT_raw <- fread("FACS_macrophages_microglia_verification.csv")
#2. Removing unnecssary variables, adjusting preserved for NA and comma-> dot separation
DT <- data.table(DT_raw[,1:2], suppressWarnings(data.table(do.call(cbind, lapply(DT_raw[,.(Expression, `Mean Cq`)], function(column){numeric_adjust(column)})))))
#3. Separating RH.index and cell type
DT <- DT[,`:=`(RH.index=substr(Sample, 1, 3), cell_type=substr(Sample, 4,nchar(Sample)))][,!"Sample"]
#4. Removing Actb
DT <- DT[Target!="ActB"]
#5. Removing all observations with Mean Cq > 35
DT <- DT[`Mean Cq`<=35]
```

```{r error=FALSE, message=FALSE, warning=FALSE, echo=FALSE}


```









